repos:
- repo: https://github.com/psf/black
  rev: v22.3.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/flake8
  rev: v4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/PyCQA/bandit
  rev: v2.1.0
  hooks:
  - id: bandit

-   repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell --ignore-words ignore-spelling-words.txt readme.md code.py
        language: python
        types: [text]